# Generated by Django 3.0.7 on 2020-07-06 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('schema_name', models.CharField(max_length=255)),
                ('primary_key', models.CharField(max_length=255)),
                ('columns', models.CharField(max_length=5000)),
                ('query_count', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='View',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('tables', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyground.Table')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('question_text', models.CharField(max_length=5000)),
                ('asker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pyground.User')),
                ('view', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pyground.View')),
            ],
        ),
    ]
